### PR TITLE
Add getElementsByClassName function to legacy.ts

### PR DESCRIPTION
**Pull request by censujiang**

### CODE REVIEW

**Comment by fb55** [comment]
Hi @censujiang, thanks for the contribution! Could you add a simple test case to the legacy spec?

**Comment by lookus69** [comment]
will it be possible with this function get elements with multiple classes? using getElement() with options = {'class': 'className'} doesnt work fine now if the element has more than one class

**Comment by fb55** [comment]
> will it be possible with this function get elements with multiple classes? using `getElement()` with `options = {'class': 'className'}` doesnt work fine now if the element has more than one class

The easiest way to do this would be to use css-select, or to supply a custom function that checks if there is match for the class.

**Comment by fb55** [comment]
Thanks @censujiang!

**Pull request merged**
